image:
  file: Dockerfile

ports:
  - port: 3000-8999
    onOpen: ignore

vscode:
  extensions:
    - scala-lang.scala@0.5.0:3FIiaU1vnooQsX3PkBlBvQ==
    - scalameta.metals@1.10.1:1859602ae77bcd603d58d72313b8a590