image:
  file: Dockerfile

ports:
  - port: 3000-8999
    onOpen: ignore

vscode:
  extensions:
    - scalameta.metals@1.10.0:wOYpsld/e93zZ250A0uKHA==
    - scala-lang.scala@0.5.0:3FIiaU1vnooQsX3PkBlBvQ==