#!/bin/bash

root=$(pwd)/$(dirname "$0")

# allow testing of multiple implementations
programs_to_test=("$root/scala/target/polly")

for program in "${programs_to_test[@]}"
do
    echo TESTING: $program
    karate tests/test-*.feature --configdir=tests --env="$program" "$@" || exit 1
done